name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Install curl
        run: sudo apt-get update && sudo apt-get install -y curl

      - name: Use curl
        run: curl --version

      # Build Docker image
      - name: Build Docker image
        run: docker build -t my-server-image .

      # Run Docker container and generate output
      - name: Run Docker container
        run: docker run --rm -v ${{ github.workspace }}/output:/app/output my-server-image